### ISSUE TITLE
Search icon is too dark

### ISSUE THREAD

**Issue by Tiagoquix** [RaitaroH/YouTube-DeepDark#100]
![image](https://github.com/RaitaroH/YouTube-DeepDark/assets/30274161/b652527c-cd30-4727-afa4-7c4570d8e063)

Can barely see the 🔍 icon

I would suggest to make it white

**Comment by RaitaroH** [comment]
Cannot reproduce on my end either, including on private mode.
Likely this is a small difference in CSS from YouTube which might trickle down to me at some point.

**Comment by RaitaroH** [comment]
Yet to encounter. Will keep an eye.
