### ISSUE TITLE
Feature request: follow main color for channel name and verified icon on channel page

### ISSUE THREAD

**Issue by Tiagoquix** [RaitaroH/YouTube-DeepDark#102]
It would be cool if channel name and verified icon followed the main color.

Examples:

On video (https://www.youtube.com/watch?v=0e3GPea1Tyg):
![image](https://github.com/RaitaroH/YouTube-DeepDark/assets/30274161/c5982bb3-3714-4972-8463-12d07e6c0645)

On channel page:
![image](https://github.com/RaitaroH/YouTube-DeepDark/assets/30274161/3c6660a4-cc23-4cd0-a023-bfedb10637ce)

**Comment by RaitaroH** [comment]
I don't think this is possible without js. The theme is css only.
