### ISSUE TITLE
YT main logo and watched videos main color accent not matched

### ISSUE THREAD

**Issue by AuRiMaS666** [RaitaroH/YouTube-DeepDark#106]
Hello,

For the last couple of days or so I've noticed that the main logo and watched videos seek bar on main page and channels (on the video page itself it does work correctly) don't sync up with the theme's main color accent anymore and is default red. Same thing with the loading progress bar at the top edge of the screen, when switching between channels, don't quite remember, if that one was colorized by the theme as well.

![2024-10-26_03-37-29](https://github.com/user-attachments/assets/5bd5f737-98c9-4227-bd07-af581e523736)

**Comment by RaitaroH** [comment]
I fixed the progress bars.
The logo though... I tried. Youtube is doing a stupid amount of AB testing and have 35+ variations; it will likely break again.
