### ISSUE TITLE
White borders on video page

### ISSUE THREAD

**Issue by irgendwie** [RaitaroH/YouTube-DeepDark#11]
I'm getting this white borders on video pages, when not enabling the dark mode from youtube itself (with the dark mode they are gone):

![screenshot from 2018-08-10 15-06-00](https://user-images.githubusercontent.com/8360698/43959345-c44e9734-9cae-11e8-9241-de24ab9da779.png)

**Comment by RaitaroH** [comment]
Thank you for the bug.
