### ISSUE TITLE
Request: AdaptaNoktoBreath Colours

### ISSUE THREAD

**Issue by DakotaGunter** [RaitaroH/YouTube-DeepDark#12]
This will be the last one I'll be requesting (for now) since I only use three of the DD styles. Like the past two, I also wrote the preset for this one. Unfortunately, it's only for the Material version, since I'm unsure on how to get to the old format.

```css
/*AdaptaNoktoBreath Colours*/
		--main-color: #1abc9c;
		--main-background: #222d32;
		--second-background: #263238;
		--hover-background: #2a353b;
		--main-text: #ffffff;
		--dimmer-text: #9b9b9b;

**Comment by RaitaroH** [comment]
See on userstyles issue.
