### ISSUE TITLE
Dropdown list - dark purple not readable

### ISSUE THREAD

**Issue by DarkLord1111** [RaitaroH/YouTube-DeepDark#13]
![immagine](https://user-images.githubusercontent.com/45848763/49937511-3414c400-fed7-11e8-8ea7-ae8acbf56070.png)
![immagine](https://user-images.githubusercontent.com/45848763/49937619-9ff72c80-fed7-11e8-982b-ee6e7fce2984.png)

i suggest this solution:

.sbpqs_a {color: #e2de20 !important;} 

so that we obtain : 
![immagine](https://user-images.githubusercontent.com/45848763/49937571-66bebc80-fed7-11e8-90dc-47afd269f63e.png)

**Comment by RaitaroH** [comment]
I don't have this issue. Yet again youtube is experimenting a lot with users...

**Comment by MaximeRF** [comment]
This issue has been fixed with one of the recent update.
