### ISSUE TITLE
Body scrollbar style

### ISSUE THREAD

**Issue by IlyaGulya** [RaitaroH/YouTube-DeepDark#3]
Hi! How about to make right scrollbar the same as others on the page?
```
body::-webkit-scrollbar-thumb {
        height:56px;
        background:hsla(0, 0%, 53.3%, .4);
}
body::-webkit-scrollbar {
        width:8px;
}
```

**Comment by RaitaroH** [comment]
Wait, can you provide more info on that. Maybe some screenshots with what you want exactly. 
Also scrollbars are themed by the browser so they should be consistent.

**Comment by IlyaGulya** [comment]
With styles, suggested by me: https://i.imgur.com/8LU2HLO.png
Default behaviour: https://i.imgur.com/WNlSPov.png

**Comment by RaitaroH** [comment]
Oke, so I know what you mean know. It seems that the scrollbars in the playlist is different for some reason. Well, I will fix this right now.

**Comment by RaitaroH** [comment]
WOW, at the same time.

**Comment by IlyaGulya** [comment]
@RaitaroH not in the playlist. In the body of page

**Comment by IlyaGulya** [comment]
@RaitaroH Yeah)

**Comment by RaitaroH** [comment]
I know. I wasn't aware because I don't use chrome so...

**Comment by RaitaroH** [comment]
Does it only happen on the material version? Or does it appear in the older youtube too?

**Comment by IlyaGulya** [comment]
I don't know how to roll back to older youtube. However, youtube does not do anything with this scrollbar at all. It has default behaviour and look

**Comment by IlyaGulya** [comment]
I think, because of backwards compatibility

**Comment by RaitaroH** [comment]
I will check it out. You can go to the settings and > restore old youtube.

Also, here: 
https://github.com/RaitaroH/YouTube-DeepDark/commit/4cd0822df0a70ba9496ee9c4c1b7002415a781f6

**Comment by RaitaroH** [comment]
Yeah, its the same on the classic.
I am fixing it right now.

**Comment by RaitaroH** [comment]
Something like this:
```
body::-webkit-scrollbar-thumb
	{
		height: 150px;
		background: hsl(0, 0%, 56%);
	}
	body::-webkit-scrollbar-thumb:hover
	{
		background: hsl(0, 0%, 11%);
	}
	body::-webkit-scrollbar
	{
		width: 10px;
		background: hsl(0, 0%, 26%);
	}
```

**Comment by RaitaroH** [comment]
Fixed the classic too. Thank you for the bug report.
