### ISSUE TITLE
Checkboxes, material settings page, buttons

### ISSUE THREAD

**Issue by RaitaroH** [RaitaroH/YouTube-DeepDark#32]
Okay @RaitaroH . No idea why they serve so many interfaces...
Someone has reported that when we click the "Not interested" link and then the "TELL US WHY" link it's not possible to see if checkboxes are checked:
![yt not interested](https://user-images.githubusercontent.com/12028968/68026585-717d6e00-fcb0-11e9-960e-4767c592fa0b.png)
![yt tell us why](https://user-images.githubusercontent.com/12028968/68026588-77734f00-fcb0-11e9-9912-66654041b0a7.png)
But I don't have this issue...
And someone else has reported that the sidebar in [settings page](https://www.youtube.com/account) is not themed but again I don't have this issue. Maybe you will be able to see what's wrong.

_Originally posted by @MaximeRF in https://github.com/RaitaroH/YouTube-DeepDark/pull/30#issuecomment-548781603_

**Comment by RaitaroH** [comment]
@MaximeRF moved issue here.

+ [x] checkboxes in 'Tell us why' reasons for why video is set as not interesting;
+ [x] the 'Video removed' text I just fixed in 469de5a
+ [ ] an actual issue is the settings page, that is the "new" material page that sucks ass and I really don't wanna theme it... AGAIN.
+ [ ] also I noticed with the very recent 'amount buttons' fix from [here](https://github.com/RaitaroH/YouTube-DeepDark/commit/d43c02fb6942341195a6d970b1bc65d57dfd333f)... I also broke other buttons in other places... damn it. Example the join buttons, login buttons... [example](https://www.youtube.com/user/scishow).

Regarding issue 1: 
![image](https://user-images.githubusercontent.com/19552720/68088790-2b203e80-fe6b-11e9-9140-7e400755d93e.png)

Regarding issue 3:
Idk maybe just change the regexp to exclude the page at this point? Unless you want to fix it, or I will look at it sometime.

Regarding issue 4:
Right now I don't have time to fix these @MaximeRF so the problem is that the code from [here](https://github.com/RaitaroH/YouTube-DeepDark/commit/d43c02fb6942341195a6d970b1bc65d57dfd333f#diff-6d8994f41afb2eb4b93021b8e671b261R1059) and ofc from [here](https://github.com/RaitaroH/YouTube-DeepDark/commit/d43c02fb6942341195a6d970b1bc65d57dfd333f#diff-6d8994f41afb2eb4b93021b8e671b261R1068) overwrites [this block](https://github.com/RaitaroH/YouTube-DeepDark/commit/d43c02fb6942341195a6d970b1bc65d57dfd333f#diff-6d8994f41afb2eb4b93021b8e671b261R2283-R2301). The problem is simply that the code for join buttons (and other buttons) overwrites the one for amount stuff... Sooo idk theme every button? Nah.

**Comment by MaximeRF** [comment]
@RaitaroH I have experienced the issue 3 so I have fixed it with [this PR](https://github.com/RaitaroH/YouTube-DeepDark/pull/33).
