### ISSUE TITLE
channel name not readable

### ISSUE THREAD

**Issue by lmssieh** [RaitaroH/YouTube-DeepDark#38]
![image](https://user-images.githubusercontent.com/53446488/69868857-57cd4780-12ab-11ea-9b78-9960c351389a.png)
![image](https://user-images.githubusercontent.com/53446488/69868940-9c58e300-12ab-11ea-84f2-3dd6c5a38395.png)

this fixed it
#channel-name {color: #fff !important;}

![image](https://user-images.githubusercontent.com/53446488/69869258-9b748100-12ac-11ea-9ca8-2c72aabd51fb.png)
![image](https://user-images.githubusercontent.com/53446488/69869291-b3e49b80-12ac-11ea-9100-85851d602a39.png)

**Comment by RaitaroH** [comment]
Hey there, are you sure you are up to date? Current: `@version 3.2.3`

![image](https://user-images.githubusercontent.com/19552720/69874975-0cc02e00-12c5-11ea-8272-386afe724844.png)

![image](https://user-images.githubusercontent.com/19552720/69874998-1fd2fe00-12c5-11ea-87b0-07f3da96ee41.png)
