### ISSUE TITLE
text in search bar almost invisible (Firefox Stylus)

### ISSUE THREAD

**Issue by FreshhhHub** [RaitaroH/YouTube-DeepDark#39]
text in search bar almost invisible (Firefox Stylus)

![dark](https://user-images.githubusercontent.com/28495425/70399443-5d056180-1a24-11ea-8501-2803d6657013.png)

**Comment by RaitaroH** [comment]
I don't seem to have the issue. Make sure the theme is up-to-date. If it is and the bug persists I cannot do much because sometimes youtube changes things for only some users and not all. You can make a PR if you want.
