### ISSUE TITLE
Top left logo seems messed up.

### ISSUE THREAD

**Issue by SenpaiSharp** [RaitaroH/YouTube-DeepDark#48]
As of today, the top left Youtube logo seems messed up. The color of the Red Play won't change with the theme and the letter color is wrong.

![youtube](https://user-images.githubusercontent.com/36146858/97357847-c5de0e00-1870-11eb-840e-81321d9f09c2.png)

**Comment by SenpaiSharp** [comment]
Of note, it's not doing this at the moment but I'm not going to close yet, as it wouldn't be the first time a youtube update has been inconsistently delivered to me.

**Comment by RaitaroH** [comment]
Cannot reproduce. Most likely as you said, you are a guinea pig for youtube ¯\\\_(ツ)_/¯

**Comment by SenpaiSharp** [comment]
Haven't seen it in a few days, gonna close for now.
