### ISSUE TITLE
Checkbox in setting isn’t styled when YouTube's native dark theme is on

### ISSUE THREAD

**Issue by Geeyun-JY3** [RaitaroH/YouTube-DeepDark#49]
See the GIF below:
![gif](https://user-images.githubusercontent.com/49396421/104427816-aaa4b400-55be-11eb-8203-646edb34a6bf.gif)

**Comment by RaitaroH** [comment]
Can you tell me where this is exactly?

**Comment by Geeyun-JY3** [comment]
Oh there is something different with the v3.4.3. At least I can if the checkbox is checked. But the checkboxes still don't follow the main color.
Settings > Playback and performance
![image](https://user-images.githubusercontent.com/49396421/108649800-0422cb80-74f9-11eb-8280-dd2e96b3f4aa.png)

**Comment by RaitaroH** [comment]
![image](https://user-images.githubusercontent.com/19552720/108678428-bb1c4880-74f3-11eb-9b90-cc410cb2f12f.png)
I added code for the checkboxes but I do not have "AVI settings" could you open the Inspector Tool and try to find the selector for that red checkbox you have there? You can edit the colors directly in the inspector by replacing the var() that youtube has with `var(--main-color)`. For example:
```
background-color: var(--main-color);
border-color: var(--main-color);
```

![image](https://user-images.githubusercontent.com/19552720/108678632-00407a80-74f4-11eb-8897-14230972b0de.png)

**Comment by Geeyun-JY3** [comment]
@RaitaroH The radio buttons of "AVI settings" work fine. The only problem is the checkboxes.

**Comment by RaitaroH** [comment]
Ok then. I will close this.
