### ISSUE TITLE
Colour fix for 9anime theme

### ISSUE THREAD

**Issue by shonay** [RaitaroH/YouTube-DeepDark#54]
Is it possible to change the background-hover colour for the Notification section?

I absolutely love the 9anime theme - its just the only problem I have is that the purple colour is too dark when hovering over items in the Notification section (clicking the bell in the top right to display the menu and when moving your mouse over each item in that list - the lighter background with the dark purple text collides and makes the selected item hard to read)

I'm sure this is probably a simple fix, I just don't know what custom css to add (if any).
Please can you help me with this?

**Comment by RaitaroH** [comment]
You don't need to change any of the css. In Stylus dropdown, for any of my deepdark themes, select as preset theme "Custom", then change all custom colors to be what you need (I will put below what you can use). This way you can keep updates for the theme and still have the colors you want.

```css
			--main-color: #723f8c;
			--main-background: #0b0a0d;
			--second-background: #17151c;
			--hover-background: #1E1c25;
			--main-text: #f9f6fb;
			--dimmer-text: #cac0cf;
```
