### ISSUE TITLE
Subscribe button no longer correct color

### ISSUE THREAD

**Issue by TernaryC** [RaitaroH/YouTube-DeepDark#55]
As of today, I've noticed the Subscribe button stays the usual Youtube red color, no matter what theme I use. (Tested on all DeepDark variants, screenshot shows Vertex Dark)
![image](https://user-images.githubusercontent.com/36998960/114472844-afc2d080-9bb8-11eb-8703-72930f6279a1.png)
On subscribed channels, it still turns the correct color for the theme (dark grey, in this case).

**Comment by RaitaroH** [comment]
Yeah they changed it. I fixed it.

**Comment by RaitaroH** [comment]
Btw, you can make the buttons gray at all times rather than blue. Check theme settings for toggles.
