### ISSUE TITLE
Support to install style as a userscript

### ISSUE THREAD

**Issue by TheMadRuffian** [RaitaroH/YouTube-DeepDark#57]
There was this option in userstyles.org for the classic version of this theme to install as a userscript. It would be nice to have it  for the new version directly from github.

![2021-05-03_05-37](https://user-images.githubusercontent.com/42994263/116832261-d1204680-abd1-11eb-8150-a9ef3361aec9.png)

**Comment by RaitaroH** [comment]
Well, I abandoned userstyles site. Those versions are out-of-date.
I also don't maintain the classic version anymore, but you can simply click on the user.css file in this repo, then click "Raw" file to get you to the installation page.
