### ISSUE TITLE
Color name text for Mod, Member and Non-Member

### ISSUE THREAD

**Issue by rpoe70** [RaitaroH/YouTube-DeepDark#65]
How to disable this? Its so hard to distinguish mod and member when watching livestream on youtube.
I'm use this theme from Enchancer for Youtube

**Comment by RaitaroH** [comment]
Can you show me what you mean (including a link to a stream)? Also @MaximeRF  is taking the theme from here, I am not supporting it directly.

**Comment by irshadali0315** [comment]
https://github.com/RaitaroH/YouTube-DeepDark/issues/65#issue-980419695
