### ISSUE TITLE
Major performance issues when modifying DOM

### ISSUE THREAD

**Issue by magnus-ISU** [RaitaroH/YouTube-DeepDark#68]
I have an extension, [Translate this Page](https://github.com/FilipePS/Traduzir-paginas-web) which when double clicking text inserts a popup that allows you to translate the selected text.

After installing this theme with Stylus, I try doing the same and there is significant lag, like several seconds, before input is registered once the extension tries to create the popup.

How can I debug what causes this, as without that I really love the theme and would like to use it.

**Comment by RaitaroH** [comment]
I have tried this on firefox (not in chrome) with the latest everything. I don't see much difference between youtube page and any other page.
I am not sure if the length of my theme is causing any problems or not; you could check if there is any lagging github for example with [this theme](https://github.com/StylishThemes/GitHub-Dark).

Nevertheless, this is more a problem with either [Stylus](https://github.com/openstyles/stylus), the Translate addon or your browser. But again, I don't have any issues.

**Comment by RaitaroH** [comment]
I will close this as I don't see what can be done on my end.

**Comment by magnus-ISU** [comment]
I'm not sure what was happening, but I just reinstalled the theme, and it doesn't seem to be happening anymore. So yeah, I don't know what was happening. It was definitely related to the theme because turning it on/off would introduce or stop the problem. But I don't have it anymore.

Thanks for the quick reply.
