### ISSUE TITLE
[BUG] Notification Number icon not matching color theme as it once did

### ISSUE THREAD

**Issue by BobbyBaratheon** [RaitaroH/YouTube-DeepDark#71]
![image](https://user-images.githubusercontent.com/85140081/162325602-7ae28607-097a-4817-bae0-be651f91ad4d.png)
Theme is set to orange dark, this number icon indicating number of notifications used to match the theme, now it is just showing as red.

**Comment by RaitaroH** [comment]
Have you updated the theme?
See commit 3301de4

**Comment by BobbyBaratheon** [comment]
I use the youtube enhancer extension by the maxime guy.

**Comment by RaitaroH** [comment]
@MaximeRF can you verify?
