### ISSUE TITLE
Where's the "Purple-Dark" preset?

### ISSUE THREAD

**Issue by ozberkcan** [RaitaroH/YouTube-DeepDark#72]
I am using the Enhancer for Youtube extension,and i am using the dark theme there made by you with the "Purple-Dark" preset. But in the .css files here and in stylus,i can't see it. Did it get removed?

**Comment by RaitaroH** [comment]
Hmm, you mean the 9anime preset? The Ubuntu purple perhaps?

**Comment by ozberkcan** [comment]
It is very similar to the 9anime preset but everything is a lot brighter

**Comment by RaitaroH** [comment]
Then I don't know. Maybe @MaximeRF added it.
Nonetheless, feel free to use the Custom option to achieve the exact look you wish.
