### ISSUE TITLE
Video added to playlist text color and like color in Shorts

### ISSUE THREAD

**Issue by Tiagoquix** [RaitaroH/YouTube-DeepDark#73]
I use this theme directly from Enhancer for YouTube, so I'm not sure if these issues are already fixed.

Anyway, I'll let you know of the problems.

1) When I add a video to a custom playlist, the text shown is in black, despite the background already being black. Can you make the text white/gray?
![image](https://user-images.githubusercontent.com/30274161/166409912-19ea2028-d2b1-4811-977c-ffba705dcbe4.png)
The text is in Brazilian Portuguese, but I think that language doesn't matter.

2) The like button in the Shorts section doesn't get colored the same way as a like in a normal video.

![image](https://user-images.githubusercontent.com/30274161/166409998-e3c031bc-c68d-4479-9b6c-8ffd57eec292.png)
![image](https://user-images.githubusercontent.com/30274161/166410025-48b77f70-3a27-430c-8dac-9308051dda22.png)

When hovering over it in the Shorts section, it works flawlessly:
![image](https://user-images.githubusercontent.com/30274161/166410053-892e86b0-4547-45b4-903e-3fbcaf478569.png)

I think that this problem (number two) is a problem with the extension itself. So I will mention @MaximeRF as well.

That's all. Thank you for your attention.

**Comment by RaitaroH** [comment]
Thanks for the issue report. Unfortunately when it comes to youtube, they are always testing different things on users.
In your case perhaps consider turning the dark theme on, in the youtube settings (top corner, your avatar icon).

1. Not the case for me yet:
![image](https://user-images.githubusercontent.com/19552720/167246113-cc4f9743-b884-4de8-aae2-ebeebaefb48c.png)
![image](https://user-images.githubusercontent.com/19552720/167246098-c5c55cd0-540f-4493-a188-c76fff1db1c5.png)

2. Also, doesn't seem to be the case for me yet. Hover also works as expected:
![image](https://user-images.githubusercontent.com/19552720/167246020-31b27756-9264-4cec-a07f-23f2896837b9.png) 
![image](https://user-images.githubusercontent.com/19552720/167246124-0f3a4037-896f-4a5d-b091-b327662b589c.png)

**Comment by RaitaroH** [comment]
I have nothing to do with the Enhancer theme. I have tested the most recent version found on this github repo.
But again, youtube has many different versions they are testing. So is entirely possible you just have one such version. If the problem will occur on my end, I will try to fix it when that time comes.
