### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by Sneffel** [RaitaroH/YouTube-DeepDark#88]
Hi. On my phone most colours aren't affected. Could you implement smaller screen sizes?

**Comment by RaitaroH** [comment]
I have no intention on porting this on mobile.
Media queries (for size) are done by youtube, as such the theme technically works on smaller screen sizes (in the inspector)
Addons only work on some browsers as well.

**Comment by Sneffel** [comment]
> the theme technically works on smaller screen sizes (in the inspector)
No, it does not. Have you checked m.youtube.com with a phone user agent?
![Screen Shot 2023-01-10 at 07 36 35](https://user-images.githubusercontent.com/9219144/211490061-6cb4ec20-e65a-48d3-ad6d-70a8e6ab2fb6.png)
It looks kind bad ngl
>  Addons only work on some browsers as well.
I got stylus working on my phone, so

**Comment by RaitaroH** [comment]
> No, it does not. Have you checked m.youtube.com with a phone user agent?

As I mentioned, in the inspector.
>  Media queries (for size) are done by youtube, as such the theme technically works on smaller screen sizes (in the inspector)

![image](https://user-images.githubusercontent.com/19552720/211550557-13e266fc-904d-4ca8-9f74-bd1288db670b.png)

I was not aware of `m.youtube.com`. Nevertheless, `m.youtube.com` on non-mobile redirects to `https://www.youtube.com/?app=desktop`, making any development on this more difficult.

>  It looks kind bad ngl

Youtube doesn't care about the website. They push people onto the app.
If there are any conflicts between the desktop theme and mobile page, you can disable the theme.

I don't use the website; I don't think most people do.
If anybody, including you, makes a PR for this, I will review it for merging. But, I will not provide support for the mobile site.

**Comment by Sneffel** [comment]
> I was not aware of `m.youtube.com`. Nevertheless, `m.youtube.com` on non-mobile redirects to `https://www.youtube.com/?app=desktop`, making any development on this more difficult.

That's why you paste the user agent in the top
