### ISSUE TITLE
Video Description Color

### ISSUE THREAD

**Issue by denn0h** [RaitaroH/YouTube-DeepDark#90]
I'm using the Purple Dark theme through YouTube Enhancer. At some point in the last few days, the description text color changed from white to purple. Up to that point only channel names and some other minor text elements were purple. I much preferred the white color for the video description.
This happens with other variants of DeepDark as well, the accent color (wrongfully?) affects the video description text.

**Comment by RaitaroH** [comment]
Fixed on master. @MaximeRF will have to update in YouTube Enhancer.

**Comment by denn0h** [comment]
Thanks for the reply 😃
