### ISSUE TITLE
[bug] Chrome scrollbar-width issue

### ISSUE THREAD

**Issue by XCanG** [RaitaroH/YouTube-DeepDark#92]
Hello, recently I upgraded Chrome version to latest and Chrome added support for [`scrollbar-width`](https://caniuse.com/mdn-css_properties_scrollbar-width)

Previously this setting only affected Firefox, but now it also affect Chrome, however, there is issue with it. All styles that applying to Firefox scrollbar have `-moz-` prefixes and when Chrome used `scrollbar-width: thin` it remove all Chrome-related scrollbar styles (like `::-webkit-scrollbar`), so they not working anymore. This break YouTube custom scrollbars.

I used this style within [Enhancer for YouTube](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) addon.

If I remove addon styles you will see scrollbar like that:
![image](https://github.com/RaitaroH/YouTube-DeepDark/assets/4011523/1fee2b6a-5d21-4f5f-81b1-a3bca5962b2d)

However if I apply them again it will make them looks like classic Windows scrollbars, except being thin:
![image](https://github.com/RaitaroH/YouTube-DeepDark/assets/4011523/daaffe54-35fa-4ac5-be14-d87ac67271cf)

The issue come from this line:
![image](https://github.com/RaitaroH/YouTube-DeepDark/assets/4011523/1cb3d659-437b-4694-abc6-36281753a2b1)

Within your styles it probably this line:
https://github.com/RaitaroH/YouTube-DeepDark/blob/master/YouTubeDeepDarkMaterial.user.css#L362C3-L362C36

**Comment by RaitaroH** [comment]
Hello,

That particular line was a fallback. 
Lower in the code, [here](https://github.com/RaitaroH/YouTube-DeepDark/blob/master/YouTubeDeepDarkMaterial.user.css#L387) to be precise, is what is supposed to theme the scrollbars. After testing in chromium 115.0 I cannot reproduce. The code changes the color and width according to variables set in Stylus.

![image](https://github.com/RaitaroH/YouTube-DeepDark/assets/19552720/f6978e56-ba15-4266-92ae-4077d549ef51)


You have brought to my attention that I should remove that scrollbar code nonetheless.
