### ISSUE TITLE
No hover over behavior for action buttons.

### ISSUE THREAD

**Issue by simsrw73** [RaitaroH/YouTube-DeepDark#96]
I guess this could be a stylistic choice, but I like YT default themes use of hover over on the action buttons under the video (thumbs up/down, share, etc.) None of the themes here seem to have any hover over behavior defined for the action buttons. I prefer the feedback that it offers. Not sure if it was an intentional omission?

**Comment by RaitaroH** [comment]
The hover on some elements was too dark to notice.
