### ISSUE TITLE
theme does not affect the scrollbar

### ISSUE THREAD

**Issue by Fan4eGGG** [RaitaroH/YouTube-DeepDark#97]
Good day.
i have a theme installed via Stylus (version 4.1.5) and recently noticed that whatever i change in the theme settings does not affect the scrollbar. and on the trends page it looks weird, [like this](https://prnt.sc/HhjtdsC5VlSc).
how to fix it?
thanks.

**Comment by RaitaroH** [comment]
Check the latest version of the theme. This looks to me like #92

**Comment by Fan4eGGG** [comment]
i have the latest ver. I don't understand what I have to do. in the theme settings in Stylus I tried to change the scrollbar color, but nothing changed.

**Comment by RaitaroH** [comment]
What browser do you use ?

**Comment by Fan4eGGG** [comment]
im on latest opera. but nvm, scrollbar changes to black after i turn on DarkReader.
