### ISSUE TITLE
Channel name doesn't follow main color anymore

### ISSUE THREAD

**Issue by Tiagoquix** [RaitaroH/YouTube-DeepDark#98]
Hi there.

I use YouTube-DeepDark with Stylus on latest Firefox on Linux.
The only thing I changed was the main color by editing the CSS file through Stylus.

Today, I noticed the channel name has turned white instead of having the main color ([example video from the screenshot](https://www.youtube.com/watch?v=Osdh9Nk2mu8)):
![image](https://github.com/RaitaroH/YouTube-DeepDark/assets/30274161/f14ed355-084d-400d-b84a-a418d9aca210)

This also happens in private windows.

Any help to revert this new behavior is appreciated.
Thanks in advance.

**Comment by RaitaroH** [comment]
I can see it on private mode.
